#!/usr/bin/env python3
"""Draft *quarantined* paper-skill scaffolds from discovery candidates.

This is the second concrete increment of HelioSI's open-ended literature
pipeline (the first is ``scripts/discover_heliophysics_literature.py``).
The discovery script emits a JSONL stream of candidate records; this
script turns selected candidates into **draft** paper-skill directories
that live OUTSIDE ``references/corpus/`` and that read as unmistakably
unverified.

Quarantine model (load-bearing)
-------------------------------
A draft produced by this script is **not** a corpus entry. It is a
non-authoritative scaffold whose only authoritative content is the
candidate metadata + abstract that the discovery backend returned. Every
draft carries quarantine markers on multiple surfaces so that a human or
agent reader cannot mistake it for a curated 501-entry paper-skill:

  - directory name prefix ``draft__`` (visible in any file listing),
  - YAML frontmatter fields ``kind: discovery-draft``,
    ``promotion_status: unreviewed``, ``verified: false``,
    ``maturity: candidate``, ``quality_level: unverified-candidate``,
    ``executable_status: unverified-draft``, ``authors_verified: false``,
  - a DRAFT / UNVERIFIED / NOT A CORPUS ENTRY banner at the top of
    ``SKILL.md`` that explicitly disclaims promotion,
  - a ``promotion_gate:`` checklist in ``metadata.yaml`` whose every
    item is ``false`` until a downstream human/agent flips it after the
    relevant evidence work,
  - an aggregate ``draft_manifest.json`` + ``draft_report.md`` at the
    drafts-dir root that also carry the quarantine banner.

The script refuses to write anywhere under ``references/corpus/`` so a
user cannot accidentally pour drafts into the curated bundle.

CLI
---
Two input modes, mutually exclusive:

  - ``--from-candidates PATH`` reads a JSONL written by
    ``discover_heliophysics_literature.py``.
  - ``--from-run-dir PATH`` reads ``PATH/candidates.jsonl`` (the run
    bundle written by the discovery script's ``--run-dir``).

By default only candidates with ``corpus_status == "new_candidate"`` are
drafted. Opt-in:

  - ``--include-unjoined``     also draft ``unjoined`` rows (no manifest
                                join performed).
  - ``--include-all-statuses`` also draft ``already_curated`` rows.
                                (Loud opt-in; the default behaviour is
                                to never draft something that already
                                exists in the curated corpus.)

The drafts-dir must be empty / non-existent unless ``--overwrite`` is
passed. Existing per-candidate draft directories are also refused
without ``--overwrite``.

Testing
-------
Companion tests under
``tests/test_draft_paper_skill_from_candidates.py`` pin the quarantine
contract: defaults, slug shape, frontmatter fields, body banner,
manifest counts, run-bundle input, collision behaviour, and the
"no drafts inside references/corpus/" rail.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import unicodedata
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple


__version__ = "0.1.0"

HERE = Path(__file__).resolve().parent
BUNDLE = HERE.parent
CORPUS_DIR = BUNDLE / "references" / "corpus"

DRAFT_FRONTMATTER_KIND = "discovery-draft"
DRAFT_PROMOTION_STATUS = "unreviewed"
DRAFT_MATURITY = "candidate"
DRAFT_QUALITY_LEVEL = "unverified-candidate"
DRAFT_EXECUTABLE_STATUS = "unverified-draft"

DEFAULT_SELECTED_STATUSES: Tuple[str, ...] = ("new_candidate",)
KNOWN_STATUSES: Tuple[str, ...] = (
    "new_candidate",
    "unjoined",
    "already_curated",
)

DRAFT_DIR_PREFIX = "draft__"
MANIFEST_FILENAME = "draft_manifest.json"
REPORT_FILENAME = "draft_report.md"
MANIFEST_SCHEMA_VERSION = "draft-scaffold-manifest/1.0"

QUARANTINE_BANNER = (
    "> **DRAFT — UNVERIFIED CANDIDATE — NOT A CORPUS ENTRY**\n"
    ">\n"
    "> This file is a non-authoritative draft generated by\n"
    "> `scripts/draft_paper_skill_from_candidates.py` from a discovery\n"
    "> candidate record. It must not be promoted to the curated 501-entry\n"
    "> paper-skill corpus, must not be cited as a verified source, and\n"
    "> must not claim paper findings beyond the imported candidate\n"
    "> metadata/abstract until the promotion gate below is completed by\n"
    "> a downstream evidence review."
)

PROMOTION_GATE_KEYS: Tuple[str, ...] = (
    "bibliographic_identity_verified",
    "provenance_checked",
    "title_authors_year_conflicts_resolved",
    "abstract_or_full_text_inspected",
    "claims_evidence_extracted",
    "data_tool_contracts_defined",
    "validation_target_recorded",
    "failure_modes_recorded",
    "maturity_tier_assigned",
)


# ---------------------------------------------------------------------------
# Slug generation
# ---------------------------------------------------------------------------

_AUTHOR_SUFFIX_RE = re.compile(r"\b(jr|sr|iii|ii|iv)\b\.?", re.IGNORECASE)
_NON_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _fold(s: str) -> str:
    if not s:
        return ""
    nfkd = unicodedata.normalize("NFKD", s)
    no_marks = "".join(c for c in nfkd if not unicodedata.combining(c))
    return no_marks.lower()


def _author_slug(authors: Optional[Sequence[str]]) -> str:
    if not authors:
        return "anon"
    raw = (authors[0] or "").strip()
    if not raw:
        return "anon"
    raw = _AUTHOR_SUFFIX_RE.sub("", raw).strip()
    tokens = [t for t in re.split(r"\s+", raw) if t and not t.endswith(".")]
    surname = tokens[-1] if tokens else raw
    folded = _fold(surname)
    cleaned = _NON_SLUG_RE.sub("-", folded).strip("-")
    return cleaned or "anon"


def _title_slug(title: Optional[str], *, max_words: int = 6) -> str:
    if not title:
        return "untitled"
    folded = _fold(title)
    cleaned = _NON_SLUG_RE.sub("-", folded).strip("-")
    parts = [p for p in cleaned.split("-") if p]
    if not parts:
        return "untitled"
    return "-".join(parts[:max_words])


def _id_hash(record: Dict) -> str:
    seed = record.get("id") or json.dumps(record, sort_keys=True, default=str)
    return hashlib.sha1(seed.encode("utf-8")).hexdigest()[:6]


def generate_slug(record: Dict) -> str:
    """Deterministic, filesystem-safe, collision-aware draft slug.

    Shape: ``draft__<author>__<year>__<title>__<hash6>``. The ``draft__``
    prefix is the headline visual quarantine marker; the hash suffix is
    derived from the candidate ``id`` (the discovery dedupe key) so two
    candidates that happen to share author + year + title still produce
    distinct slugs.
    """
    author = _author_slug(record.get("authors"))
    year = record.get("year")
    year_str = str(year) if year is not None else "noyear"
    title = _title_slug(record.get("title"))
    suffix = _id_hash(record)
    return f"{DRAFT_DIR_PREFIX}{author}__{year_str}__{title}__{suffix}"


# ---------------------------------------------------------------------------
# Input loading
# ---------------------------------------------------------------------------

def load_candidates(path: Path) -> List[Dict]:
    """Load candidate records from a JSONL file. Comments/blank lines ignored."""
    out: List[Dict] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise SystemExit(
                    f"draft_paper_skill_from_candidates: bad JSONL line "
                    f"{path}:{line_no}: {e}"
                ) from None
    return out


def load_candidates_from_run_dir(run_dir: Path) -> List[Dict]:
    """Read ``<run_dir>/candidates.jsonl`` (the discovery run-bundle layout)."""
    candidates_path = run_dir / "candidates.jsonl"
    if not candidates_path.is_file():
        raise SystemExit(
            f"draft_paper_skill_from_candidates: run-dir is missing "
            f"candidates.jsonl: {candidates_path}"
        )
    return load_candidates(candidates_path)


# ---------------------------------------------------------------------------
# Selection
# ---------------------------------------------------------------------------

def select_candidates(
    records: Sequence[Dict],
    *,
    include_unjoined: bool = False,
    include_all_statuses: bool = False,
) -> Tuple[List[Dict], List[Dict]]:
    """Split records into (selected, skipped).

    Defaults: only ``corpus_status == "new_candidate"`` is selected.
    Records without a ``corpus_status`` are treated as ``unjoined``.
    ``--include-all-statuses`` is the only switch that admits
    ``already_curated`` rows.
    """
    allowed = set(DEFAULT_SELECTED_STATUSES)
    if include_unjoined:
        allowed.add("unjoined")
    if include_all_statuses:
        allowed.update(KNOWN_STATUSES)

    selected: List[Dict] = []
    skipped: List[Dict] = []
    for rec in records:
        status = rec.get("corpus_status") or "unjoined"
        if status in allowed:
            selected.append(rec)
        else:
            skipped.append(rec)
    return selected, skipped


def _counts_by_status(records: Sequence[Dict]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for rec in records:
        status = rec.get("corpus_status") or "unjoined"
        counts[status] = counts.get(status, 0) + 1
    return counts


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _format_authors_list(authors: Optional[Sequence[str]]) -> List[str]:
    if not authors:
        return []
    return [str(a).strip() for a in authors if str(a).strip()]


_YAML_RESERVED = {"null", "true", "false", "yes", "no", "~", "on", "off"}


def _yaml_str(value) -> str:
    """Render a scalar for YAML output. Quoted when ambiguous."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value)
    if s == "":
        return '""'
    needs_quote = (
        any(c in s for c in ":#\n\"'")
        or s != s.strip()
        or s.lower() in _YAML_RESERVED
    )
    if not needs_quote:
        return s
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _yaml_list(values: Sequence[str], indent: str = "  ") -> str:
    if not values:
        return " []"
    lines = [""]
    for v in values:
        lines.append(f"{indent}- {_yaml_str(v)}")
    return "\n".join(lines)


def render_skill_md(record: Dict, *, slug: str) -> str:
    """Render the draft SKILL.md body."""
    title = record.get("title") or "(untitled candidate)"
    year = record.get("year")
    doi = record.get("doi")
    arxiv_id = record.get("arxiv_id")
    bibcode = record.get("bibcode")
    url = record.get("url")
    source = record.get("source")
    query = record.get("query")
    discovered_at = record.get("discovered_at_utc")
    abstract = record.get("abstract")
    topic_tags = record.get("topic_tags") or []
    authors = _format_authors_list(record.get("authors"))
    corpus_status = record.get("corpus_status") or "unjoined"
    dedupe_id = record.get("id")

    fm_lines = [
        "---",
        f"name: {slug}",
        f"kind: {DRAFT_FRONTMATTER_KIND}",
        f"promotion_status: {DRAFT_PROMOTION_STATUS}",
        "verified: false",
        f"maturity: {DRAFT_MATURITY}",
        f"quality_level: {DRAFT_QUALITY_LEVEL}",
        f"executable_status: {DRAFT_EXECUTABLE_STATUS}",
        "authors_verified: false",
        f"source_corpus_status: {corpus_status}",
        "---",
    ]
    frontmatter = "\n".join(fm_lines)

    prov_lines = [
        f"- **Title (candidate, unverified):** {title}",
        f"- **Year (candidate, unverified):** "
        f"{year if year is not None else 'TODO_verify'}",
        f"- **DOI:** {doi if doi else 'TODO_verify (not present in candidate)'}",
        f"- **arXiv:** {arxiv_id if arxiv_id else 'TODO_verify (not present in candidate)'}",
        f"- **ADS bibcode:** {bibcode if bibcode else 'TODO_verify (not present in candidate)'}",
        f"- **URL/source/backend:** {url or '(none)'} "
        f"(backend: `{source or 'unknown'}`)",
    ]
    if authors:
        prov_lines.append("- **Authors (candidate, unverified):**")
        for a in authors:
            prov_lines.append(f"  - {a}")
    else:
        prov_lines.append(
            "- **Authors (candidate, unverified):** "
            "(none returned by backend; TODO_verify)"
        )
    if topic_tags:
        prov_lines.append(
            f"- **Discovery topic tags:** {', '.join(topic_tags)}"
        )
    prov_lines.append(f"- **Discovery query:** {query or '(unknown)'}")
    prov_lines.append(f"- **Discovery backend:** {source or '(unknown)'}")
    prov_lines.append(
        f"- **Discovered at (UTC):** {discovered_at or '(unknown)'}"
    )
    prov_lines.append(
        f"- **Discovery dedupe id:** `{dedupe_id or '(unknown)'}`"
    )
    prov_lines.append(
        f"- **Discovery corpus_status:** `{corpus_status}`"
    )
    provenance_block = "\n".join(prov_lines)

    abstract_block = (
        f"> {abstract}"
        if abstract
        else "> (no abstract returned by the discovery backend; "
             "TODO_verify by fetching the paper directly)"
    )

    body = f"""{frontmatter}

{QUARANTINE_BANNER}

# {title}

> Draft scaffold compiled from a discovery candidate. Do not assert
> paper findings beyond the abstract below until the promotion gate at
> the bottom of this file is completed by a downstream evidence review.

## Candidate provenance (imported from discovery; unverified)

{provenance_block}

## Candidate abstract (imported verbatim from discovery backend)

{abstract_block}

## Layer 1 — Scientific invariant (TODO; do not invent)

Describe the load-bearing scientific claim the paper actually makes, as
stated in the paper itself. Quote or paraphrase only after the full text
has been read and the claim/evidence boundary is recorded in the
promotion gate. Until then, this section MUST be left as a TODO and the
draft remains non-authoritative.

- TODO: read the full text and extract the Layer-1 invariant.
- TODO: record the claim/evidence boundary (what the paper proves vs.
  what it merely paraphrases from prior work).

## Layer 2 — Executable protocol / capability contract (TODO)

- TODO: define data/tool contracts (instrument, cadence, level, archive).
- TODO: define the algorithm or workflow steps as composable units.
- TODO: define inputs/outputs of each step and the failure semantics.

## Layer 3 — Adapter / runtime binding (TODO)

- TODO: identify example adapter bindings (MCPs, dataset clients, harness
  affordances) that would satisfy the Layer-2 contract.
- TODO: record any environment or credential prerequisites.

## Layer 4 — Research-generation affordance (TODO)

- TODO: identify gaps, tensions, hypotheses, minimal experiments, and
  composable experiments this paper enables (do not fabricate; populate
  only after the full text has been read).

## Validation TODOs (promotion gate)

This draft will remain quarantined until every item below has been
completed and the corresponding flag in `metadata.yaml::promotion_gate`
has been flipped to `true`:

- [ ] verify DOI against the publisher of record
- [ ] verify arXiv id (matches the same paper as the DOI)
- [ ] verify title (round-trips against the publisher record)
- [ ] verify authors (full list, ordering, affiliations as needed)
- [ ] fetch full text and read past the abstract
- [ ] extract claim and evidence boundary (Layer 1)
- [ ] define data/tool contracts (Layer 2)
- [ ] record a numeric or figure-level validation target
- [ ] record failure modes and load-bearing assumptions
- [ ] assign a maturity tier consistent with `references/corpus_qa_report_v2.md`

## Provenance & quarantine notes

This file is a **non-authoritative** draft scaffold. The only content
imported from the discovery backend is the bibliographic provenance block
and the abstract above. Every other section is a TODO and must not be
treated as a paper finding. Do not promote into `references/corpus/`
without completing the promotion gate above.
"""
    return body


def render_metadata_yaml(record: Dict, *, slug: str) -> str:
    """Render the draft metadata.yaml (stdlib-only YAML emission)."""
    title = record.get("title") or ""
    year = record.get("year")
    doi = record.get("doi")
    arxiv_id = record.get("arxiv_id")
    bibcode = record.get("bibcode")
    url = record.get("url")
    source = record.get("source")
    query = record.get("query")
    discovered_at = record.get("discovered_at_utc")
    authors = _format_authors_list(record.get("authors"))
    topic_tags = record.get("topic_tags") or []
    corpus_status = record.get("corpus_status") or "unjoined"
    corpus_match_via = record.get("corpus_match_via")
    corpus_match_slugs = record.get("corpus_match_slugs") or []
    corpus_match_titles = record.get("corpus_match_titles") or []
    dedupe_id = record.get("id")

    lines: List[str] = []
    lines.append(f"slug: {slug}")
    lines.append(f"kind: {DRAFT_FRONTMATTER_KIND}")
    lines.append(f"promotion_status: {DRAFT_PROMOTION_STATUS}")
    lines.append("verified: false")
    lines.append(f"maturity: {DRAFT_MATURITY}")
    lines.append(f"quality_level: {DRAFT_QUALITY_LEVEL}")
    lines.append(f"executable_status: {DRAFT_EXECUTABLE_STATUS}")
    lines.append("authors_verified: false")
    lines.append("")
    lines.append("# Candidate-derived bibliographic provenance (UNVERIFIED).")
    lines.append("# Treat every value as an import from the discovery backend,")
    lines.append("# not a verified claim. The promotion_gate below records the")
    lines.append("# gates that must be cleared before any of this is treated as truth.")
    lines.append(f"title: {_yaml_str(title)}")
    lines.append(f"year: {_yaml_str(year)}")
    lines.append(f"doi: {_yaml_str(doi)}")
    lines.append(f"arxiv: {_yaml_str(arxiv_id)}")
    lines.append(f"ads_bibcode: {_yaml_str(bibcode)}")
    lines.append(f"url: {_yaml_str(url)}")
    lines.append("authors:" + _yaml_list(authors))
    lines.append("topic_tags:" + _yaml_list(topic_tags))
    lines.append("")
    lines.append("# Discovery provenance (which discovery run produced this candidate).")
    lines.append("discovery:")
    lines.append(f"  source: {_yaml_str(source)}")
    lines.append(f"  backend: {_yaml_str(source)}")
    lines.append(f"  query: {_yaml_str(query)}")
    lines.append(f"  discovered_at_utc: {_yaml_str(discovered_at)}")
    lines.append(f"  dedupe_id: {_yaml_str(dedupe_id)}")
    lines.append(f"  corpus_status: {_yaml_str(corpus_status)}")
    lines.append(f"  corpus_match_via: {_yaml_str(corpus_match_via)}")
    lines.append(
        "  corpus_match_slugs:" + _yaml_list(list(corpus_match_slugs))
    )
    lines.append(
        "  corpus_match_titles:" + _yaml_list(list(corpus_match_titles))
    )
    lines.append("")
    lines.append("# Promotion gate. Every item must be flipped to true (by a")
    lines.append("# downstream human/agent evidence review) before this draft can")
    lines.append("# be considered for promotion into references/corpus/.")
    lines.append("promotion_gate:")
    for key in PROMOTION_GATE_KEYS:
        lines.append(f"  {key}: false")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Filesystem writers
# ---------------------------------------------------------------------------

def _refuse_if_inside_corpus(drafts_dir: Path) -> None:
    """Hard rail: drafts may never land inside references/corpus/."""
    # Resolve as far as possible. The drafts-dir need not exist yet;
    # walk parents until we find one that does.
    candidate = drafts_dir
    probe = candidate
    while not probe.exists() and probe != probe.parent:
        probe = probe.parent
    try:
        resolved_probe = probe.resolve()
        corpus_resolved = CORPUS_DIR.resolve()
    except OSError as e:
        raise SystemExit(
            f"draft_paper_skill_from_candidates: cannot resolve drafts-dir: {e}"
        ) from None
    # Re-anchor the (possibly non-existent) tail back onto the resolved
    # probe so the check is robust to symlinks above the missing tail.
    tail = candidate.relative_to(probe) if probe in candidate.parents or probe == candidate else None
    resolved = resolved_probe / tail if tail is not None else resolved_probe

    if (
        resolved == corpus_resolved
        or corpus_resolved in resolved.parents
    ):
        raise SystemExit(
            "draft_paper_skill_from_candidates: refusing to write drafts "
            f"under references/corpus/ (got {drafts_dir}). Drafts are "
            "non-authoritative quarantine artifacts; the curated corpus "
            "is for verified entries only."
        )


def write_drafts(
    selected: Sequence[Dict],
    drafts_dir: Path,
    *,
    overwrite: bool = False,
) -> List[Dict]:
    """Write one ``<slug>/SKILL.md`` + ``<slug>/metadata.yaml`` per record."""
    drafts_dir.mkdir(parents=True, exist_ok=True)
    summaries: List[Dict] = []
    for rec in selected:
        slug = generate_slug(rec)
        draft_path = drafts_dir / slug
        if draft_path.exists():
            if not overwrite:
                raise SystemExit(
                    f"draft_paper_skill_from_candidates: draft directory "
                    f"already exists (use --overwrite to allow): {draft_path}"
                )
            shutil.rmtree(draft_path)
        draft_path.mkdir(parents=True)
        (draft_path / "SKILL.md").write_text(
            render_skill_md(rec, slug=slug), encoding="utf-8"
        )
        (draft_path / "metadata.yaml").write_text(
            render_metadata_yaml(rec, slug=slug), encoding="utf-8"
        )
        summaries.append(
            {
                "slug": slug,
                "path": str(draft_path.relative_to(drafts_dir)),
                "corpus_status": rec.get("corpus_status") or "unjoined",
                "dedupe_id": rec.get("id"),
                "title": rec.get("title"),
                "year": rec.get("year"),
                "doi": rec.get("doi"),
                "arxiv_id": rec.get("arxiv_id"),
                "source": rec.get("source"),
            }
        )
    return summaries


# ---------------------------------------------------------------------------
# Manifest + report
# ---------------------------------------------------------------------------

def build_manifest(
    *,
    input_kind: str,
    input_path: Path,
    selected: Sequence[Dict],
    skipped: Sequence[Dict],
    draft_summaries: Sequence[Dict],
    cli_args: Dict,
) -> Dict:
    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "script_version": __version__,
        "input_kind": input_kind,
        "input_path": str(input_path),
        "cli_args": dict(cli_args),
        "selected_count": len(selected),
        "skipped_count": len(skipped),
        "selected_counts_by_corpus_status": _counts_by_status(selected),
        "skipped_counts_by_corpus_status": _counts_by_status(skipped),
        "promotion_gate_keys": list(PROMOTION_GATE_KEYS),
        "drafts": list(draft_summaries),
        "quarantine_disclosure": (
            "Every entry under `drafts[]` is a non-authoritative draft "
            "scaffold. Drafts must not be promoted to references/corpus/ "
            "or cited as verified sources until the per-draft "
            "promotion_gate in metadata.yaml has been completed by a "
            "downstream evidence review."
        ),
        "limits": (
            "This manifest records only what this single invocation drafted "
            "from the supplied input. It does not assert that the inputs "
            "themselves are exhaustive, novel, or correctly classified."
        ),
    }


def render_report(manifest: Dict) -> str:
    lines: List[str] = []
    lines.append("# Draft paper-skill scaffold report")
    lines.append("")
    lines.append("> **DRAFT — UNVERIFIED — NOT PROMOTED**")
    lines.append(">")
    lines.append(
        "> The artifacts listed below are non-authoritative discovery-draft "
        "scaffolds. They are not corpus entries and must not be cited as "
        "verified sources until the promotion gate in each draft's "
        "`metadata.yaml` has been completed."
    )
    lines.append("")
    lines.append(f"- **Script version:** {manifest.get('script_version')}")
    lines.append(f"- **Manifest schema:** {manifest.get('schema_version')}")
    lines.append(f"- **Input kind:** {manifest.get('input_kind')}")
    lines.append(f"- **Input path:** `{manifest.get('input_path')}`")
    lines.append("")
    lines.append("## Selected counts")
    lines.append("")
    lines.append(f"- Total selected: **{manifest.get('selected_count', 0)}**")
    for status, count in sorted(
        (manifest.get("selected_counts_by_corpus_status") or {}).items()
    ):
        lines.append(f"  - `{status}`: {count}")
    lines.append("")
    lines.append("## Skipped counts")
    lines.append("")
    lines.append(f"- Total skipped: **{manifest.get('skipped_count', 0)}**")
    for status, count in sorted(
        (manifest.get("skipped_counts_by_corpus_status") or {}).items()
    ):
        lines.append(f"  - `{status}`: {count}")
    lines.append("")
    lines.append("## Draft directories")
    lines.append("")
    drafts = manifest.get("drafts") or []
    for d in drafts:
        lines.append(
            f"- `{d.get('path')}` — corpus_status=`{d.get('corpus_status')}` "
            f"— dedupe_id=`{d.get('dedupe_id')}`"
        )
    if not drafts:
        lines.append("- (no drafts written)")
    lines.append("")
    lines.append("## Promotion gate (every item must be cleared per draft)")
    lines.append("")
    for key in manifest.get("promotion_gate_keys") or []:
        lines.append(f"- `{key}`")
    lines.append("")
    lines.append("## Limits (honest framing)")
    lines.append("")
    lines.append(
        manifest.get("quarantine_disclosure")
        or "Drafts are non-authoritative quarantine artifacts."
    )
    lines.append("")
    lines.append(manifest.get("limits") or "")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

EPILOG = """\
Examples:
  # Draft only new_candidate rows from a JSONL emitted by discovery:
  python3 scripts/draft_paper_skill_from_candidates.py \\
      --from-candidates /tmp/cand.jsonl --drafts-dir /tmp/drafts

  # Read from a run bundle (--run-dir output of the discovery script):
  python3 scripts/draft_paper_skill_from_candidates.py \\
      --from-run-dir /tmp/discovery-run-2026-05-19 \\
      --drafts-dir /tmp/drafts

  # Also draft unjoined rows (novelty join disabled at discovery time):
  python3 scripts/draft_paper_skill_from_candidates.py \\
      --from-candidates /tmp/cand.jsonl --drafts-dir /tmp/drafts \\
      --include-unjoined

Drafts are NOT corpus entries. They live in the --drafts-dir you pick;
they are never written under references/corpus/. Read the per-draft
metadata.yaml::promotion_gate before promoting anything.
"""


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="draft_paper_skill_from_candidates.py",
        description=(
            "Generate quarantined draft paper-skill scaffolds from "
            "discovery candidate records. Drafts live OUTSIDE "
            "references/corpus/ and must not be promoted without "
            "completing the per-draft promotion gate."
        ),
        epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--drafts-dir", required=True,
        help="Directory to write drafts into. Must not be inside "
             "references/corpus/.",
    )
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument(
        "--from-candidates",
        help="Path to a candidate JSONL emitted by "
             "scripts/discover_heliophysics_literature.py.",
    )
    src.add_argument(
        "--from-run-dir",
        help="Path to a discovery run-bundle directory "
             "(reads <run-dir>/candidates.jsonl).",
    )
    p.add_argument(
        "--include-unjoined", action="store_true",
        help="Also draft rows with corpus_status='unjoined'. Off by default.",
    )
    p.add_argument(
        "--include-all-statuses", action="store_true",
        help="Also draft rows with corpus_status='already_curated'. "
             "Off by default; loud opt-in.",
    )
    p.add_argument(
        "--overwrite", action="store_true",
        help="Allow re-writing existing draft directories under "
             "--drafts-dir. Off by default; the script never silently "
             "clobbers prior drafts.",
    )
    p.add_argument(
        "--quiet", action="store_true",
        help="Suppress the human-readable stderr summary.",
    )
    p.add_argument(
        "--version", action="version",
        version=f"draft_paper_skill_from_candidates {__version__}",
    )
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _build_parser().parse_args(argv)

    drafts_dir = Path(args.drafts_dir)
    _refuse_if_inside_corpus(drafts_dir)

    if args.from_candidates:
        input_kind = "candidates-jsonl"
        input_path = Path(args.from_candidates)
        records = load_candidates(input_path)
    else:
        input_kind = "run-bundle"
        input_path = Path(args.from_run_dir)
        records = load_candidates_from_run_dir(input_path)

    selected, skipped = select_candidates(
        records,
        include_unjoined=bool(args.include_unjoined),
        include_all_statuses=bool(args.include_all_statuses),
    )

    draft_summaries = write_drafts(
        selected, drafts_dir, overwrite=bool(args.overwrite)
    )

    manifest = build_manifest(
        input_kind=input_kind,
        input_path=input_path,
        selected=selected,
        skipped=skipped,
        draft_summaries=draft_summaries,
        cli_args={
            "drafts_dir": str(drafts_dir),
            "from_candidates": args.from_candidates,
            "from_run_dir": args.from_run_dir,
            "include_unjoined": bool(args.include_unjoined),
            "include_all_statuses": bool(args.include_all_statuses),
            "overwrite": bool(args.overwrite),
        },
    )

    manifest_path = drafts_dir / MANIFEST_FILENAME
    report_path = drafts_dir / REPORT_FILENAME
    with manifest_path.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2, sort_keys=False)
        f.write("\n")
    report_path.write_text(render_report(manifest), encoding="utf-8")

    if not args.quiet:
        sys.stderr.write(
            f"draft_paper_skill_from_candidates: wrote "
            f"{len(draft_summaries)} draft(s) under {drafts_dir} "
            f"(skipped {len(skipped)}); manifest={manifest_path}\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
